//! Cloud backup orchestration.
//
// Assembles the NON-SECRET backup manifest (aliases, labels, db paths — never a
// seed), hands it to the Rust core's `backupEncrypt` (which injects each seed
// internally and returns an opaque blob), and stores the blob in the user's own
// cloud via the native `cloud-backup` module. Restore is the reverse. This file
// never touches plaintext seed bytes.
//
// Factory over injected `core` (Rust) + `cloud` (native) seams so the
// orchestration is unit-testable without the FFI or a real cloud.

/** One account's display state (mirrors the Rust `BackupAccount` record). */
export interface BackupAccount {
  index: number;
  name: string;
  hidden: boolean;
}

/** A wallet to back up (mirrors the Rust `BackupWalletInput` record). `dbPath`
 *  locates the seed sidecar Rust reads; `wordCount`/`hasPassphrase` are display
 *  metadata (the seed already incorporates any passphrase). */
export interface WalletDescriptor {
  alias: string;
  name: string;
  isPrimary: boolean;
  dbPath: string;
  wordCount: number;
  hasPassphrase: boolean;
  accounts: BackupAccount[];
  activeAccount: number;
  /** BIP-39 phrase (space-joined) to store ENCRYPTED in the blob, so a restored
   *  wallet can reveal it / write cards. Omitted if not available on-device. */
  mnemonic?: string;
}

// camelCase to match the ubrn-generated uniffi records exactly (uniffi-bindgen
// converts the Rust snake_case fields to camelCase in the TS bindings).
export interface BackupWalletInput {
  alias: string;
  dbPath: string;
  name: string;
  isPrimary: boolean;
  wordCount: number;
  hasPassphrase: boolean;
  accounts: BackupAccount[];
  activeAccount: number;
  // Required key (may be undefined) to match the ubrn-generated `Option<String>`.
  mnemonic: string | undefined;
}
export interface BackupManifestInput {
  version: number;
  activeWallet: string;
  wallets: BackupWalletInput[];
}
export interface BackupRestoreTarget {
  alias: string;
  dbPath: string;
}
export interface RestoredWallet {
  alias: string;
  name: string;
  isPrimary: boolean;
  accounts: BackupAccount[];
  activeAccount: number;
  /** Phrase recovered from the blob (if backed up), to persist on this device. */
  mnemonic?: string;
}
export interface BackupManifestMeta {
  version: number;
  activeWallet: string;
  wallets: RestoredWallet[];
}

/** The Rust core's exported backup surface (camelCase generated by ubrn). */
export interface BackupCore {
  backupEncrypt(keystore: unknown, password: string, manifest: BackupManifestInput): Promise<Uint8Array>;
  restoreFromBackup(
    keystore: unknown,
    blob: Uint8Array,
    password: string,
    targets: BackupRestoreTarget[],
  ): Promise<BackupManifestMeta>;
}

/** The native cloud blob store (the `cloud-backup` module). */
export interface CloudStore {
  putBlob(id: string, bytes: Uint8Array): Promise<void>;
  getBlob(id: string): Promise<Uint8Array | null>;
  deleteBlob(id: string): Promise<void>;
  isAvailable(): Promise<boolean>;
}

/** Single backup object per identity for v1 (the primary wallet's manifest). */
export const MANIFEST_ID = 'mercury.wallet.backup.v1';

/** Build the non-secret manifest the Rust core encrypts. Pure + testable. */
export function assembleManifest(wallets: WalletDescriptor[], activeWallet: string, version: number): BackupManifestInput {
  return {
    version,
    activeWallet,
    wallets: wallets.map((w) => ({
      alias: w.alias,
      dbPath: w.dbPath,
      name: w.name,
      isPrimary: w.isPrimary,
      wordCount: w.wordCount,
      hasPassphrase: w.hasPassphrase,
      accounts: w.accounts,
      activeAccount: w.activeAccount,
      mnemonic: w.mnemonic,
    })),
  };
}

export interface Backup {
  /** Encrypt the wallets under `password` and upload to the user's cloud. */
  backup(password: string, wallets: WalletDescriptor[], activeWallet: string, version: number): Promise<void>;
  /** Fetch + decrypt the cloud backup and re-import wallets. Returns null if no backup exists. */
  restore(password: string, targets: BackupRestoreTarget[]): Promise<BackupManifestMeta | null>;
  /** Whether a backup blob exists in the user's cloud. */
  exists(): Promise<boolean>;
  /** Whether the user's cloud is usable right now (iCloud signed in / Drive scope). */
  available(): Promise<boolean>;
  /** Remove the cloud backup. */
  remove(): Promise<void>;
}

export function createBackup(deps: { keystore: unknown; core: BackupCore; cloud: CloudStore; manifestId?: string }): Backup {
  const id = deps.manifestId ?? MANIFEST_ID;
  const { keystore, core, cloud } = deps;

  return {
    async backup(password, wallets, activeWallet, version) {
      const manifest = assembleManifest(wallets, activeWallet, version);
      const blob = await core.backupEncrypt(keystore, password, manifest);
      await cloud.putBlob(id, blob);
    },
    async restore(password, targets) {
      const blob = await cloud.getBlob(id);
      if (!blob) return null; // no backup for this account → caller falls back to manual import
      return core.restoreFromBackup(keystore, blob, password, targets);
    },
    async exists() {
      return (await cloud.getBlob(id)) !== null;
    },
    available() {
      return cloud.isAvailable();
    },
    async remove() {
      await cloud.deleteBlob(id);
    },
  };
}
